// create a user model with name email, phone no, pref1 , pref2, emailSend, whatsappSend,Date

import mongoose from "mongoose";

const userSchema = new mongoose.Schema(
  {
    userName: {
      type: String,
      required: true,
    },
    email: {
      type: String,
      required: true,
    },
    password:{
        type: String,
        required: true,
    },
    otp:{
        type: String,
    },
    // payment: {
    //     type: String, //url generated by cloudinary
    // },
    // meetingBook: {
    //     type: String, //url generated by cloudinary
    // },
    // medicalDocuments: {
    //     type: String, //url generated by cloudinary 
    // }
  },
  {
    timestamps: true,
  }
);

const User = mongoose.model("User", userSchema);
export default User;
